# Generated by Django 3.1 on 2020-08-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0002_building_room_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='count',
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('count', models.IntegerField()),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_tracing.stat')),
            ],
        ),
    ]
