# Generated by Django 3.1 on 2020-08-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0003_auto_20200814_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='time',
            new_name='time_created',
        ),
    ]
