# Generated by Django 3.1 on 2020-08-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0004_auto_20200815_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='building_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
    ]
