# Generated by Django 3.1 on 2020-08-18 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0005_auto_20200815_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tested', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.FloatField()),
                ('infection_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_tracing.infectionreport')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_tracing.room')),
            ],
        ),
    ]
