# Generated by Django 3.1 on 2020-08-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0006_infectionreport_locationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectionreport',
            name='date_recorded',
            field=models.DateField(default='2020-08-09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infectionreport',
            name='time_recorded',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
