# Generated by Django 3.1 on 2020-09-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0009_auto_20200823_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='room',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
