# Generated by Django 3.1 on 2020-09-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0011_stat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
