# Generated by Django 3.1 on 2020-09-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0014_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='count_unique',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
