# Generated by Django 3.1 on 2020-09-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0015_stat_count_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Log1',
        ),
    ]
