# Generated by Django 3.1 on 2020-11-06 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0016_auto_20200921_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeakData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('rank', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_tracing.room')),
            ],
        ),
    ]
