# Generated by Django 3.1 on 2020-11-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0017_peakdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeakHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
