# Generated by Django 3.1 on 2020-11-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0018_peakhour'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_tracing.room')),
            ],
        ),
    ]
