# Generated by Django 3.1 on 2020-11-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_tracing', '0019_popdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.BinaryField()),
                ('private_key', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
